source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RocketChatAdapter_Example', :exclusive => true do
  pod 'RocketChatAdapter', :path => '../'
end

target 'RocketChatAdapter_Tests', :exclusive => true do
  pod 'RocketChatAdapter', :path => '../'

  
end
